server:
  port: 84
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
        port: 8719
        #配置Sentinel dashboard地址
        dashboard: 127.0.0.1:8080
      datasource:
        ds1:  # key
          nacos:  # 使用nacos做持久化   还支持file、Zookeeper、apollo、redis
            server-addr: localhost:8848
            dataId: cloudalibaba-sentinel-service  #必须写 不能为空
            groupId: DEFAULT_GROUP   #默认 可不用写
            data-type: json  # 默认json
            rule-type: flow  #不能为空 flow、degrade、param-flow、system、authority等


#消费者将要去访问的微服务名称(注册成功进nacos的微服务提供者)
service-url:
  nacos-user-service: http://nacos-payment-provider