server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8002          #匹配后提供服务的路由地址
          #以注册中心上微服务名为路径创建动态路由进行转发，从而实现动态路由的功能
          uri: lb://cloud-payment-service  #匹配后提供服务的路由地址 uri的协议为lb，表示启用Gateway的负载均衡功能
          predicates:
            - Path=/payment/get/**         # 断言，路径相匹配的进行路由
            - After=2022-07-05T17:03:57.249+08:00[Asia/Shanghai]
#            - Cookie=username,zzyy
          filters:
            - AddRequestParameter=X-Request-Id,1024 #过滤器工厂会在匹配的请求头加上一对请求头，名称为X-Request-Id值为1024

        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:80        #匹配后提供服务的路由地址
          predicates:
            - Path=/consumer/payment/get/**         # 断言，路径相匹配的进行路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
#      defaultZone: http://eureka7001.com:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
