server:
  port: 9001
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        # 配置nacos地址
        server-addr: 127.0.0.1:8848
# 配置Actuator的基础路径 暴露  监控
management:
  endpoints:
    web:
      exposure:
        include: '*'