server:
  port: 85
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
        port: 8719
        #配置Sentinel dashboard地址
        dashboard: 127.0.0.1:8080

# 激活Sentinel对Feign的支持
feign:
  sentinel:
    enabled: true